{
 "title": "Monitoramento",
 "description": "Flask prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(flask_http_request_total{job=\"backend\"}[$__rate_interval])",
     "legendFormat": "{{method}} - {{status }}"
    }
   ]
  },
  {
   "title": "Request duration by status code",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "sum by(status) (flask_http_request_duration_seconds_sum{job=\"backend\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process CPU seconds total",
   "type": "timeseries",
   "description": "Total user and system CPU time spent in seconds.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"backend\"}[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory bytes",
   "type": "timeseries",
   "description": "Resident memory size in bytes.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"backend\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Process open fds",
   "type": "timeseries",
   "description": "Number of open file descriptors.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "process_open_fds{job=\"backend\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}