global:
  scrape_interval: 3s

  external_labels:
    monitor: "Flask-app"

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          alias: "prometheus"

  - job_name: "backend"
    static_configs:
      - targets: ["backend:8000"]
        labels:
          alias: "backend"
