version: "3.9"
services:
  python-flask:
    build:
      context: "./"
      dockerfile: "./Dockerfile"
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app