name: Deploy para EC2 depois fazer build para ECR
on:
  workflow_run:
    workflows: ["Deploy api.py App to ECR"]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH into EC2 and run deploy script
      run: |
        ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY github@${{ secrets.EC2_PUBLIC_IP }} 'bash /local/deploy.sh'
