#cloud-config

users:
  - name: gdardengo
    groups: [ sudo ,docker ]
    sudo: [ "ALL=(ALL) NOPASSWD:ALL" ]
    shell: /bin/bash
    ssh-authorized-keys: 
        - ${ssh-key}

## copiar docker-compose.yml, deploy.sh  e prometheus config para a pasta Documents
write_files:
  - encoding: b64
    content: ${B64_DOCKER_COMPOSE}
    owner: root:root
    path: /local/api/docker-compose.yaml
    permissions: '0644'
  
  - encoding: b64
    content: ${B64_DEPLOY}
    owner: root:root
    path: /local/deploy.sh
    permissions: '0755'

  - encoding: b64
    content: ${B64_PROMETHEUS_CONFIG}
    owner: root:root
    path: /local/api/prometheus/config.yaml
    permissions: '0644'
  
runcmd:
## instalando o docker ce:
  - sudo apt-get update
  - sudo apt-get -y install ca-certificates curl gnupg lsb-release
  - sudo mkdir -p /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - sudo apt-get update
  - sudo apt-get -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin
## instalando aws cli
  - sudo apt install -y awscli
## fazer login aws
  - aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin ${AWS_ACCOUNT_NUMBER}.dkr.ecr.us-east-1.amazonaws.com 
## rodando docker compose
  - sudo docker compose -f /local/api/docker-compose.yaml up -d 
